// <auto-generated />
namespace MainOffice.Migrations.AppDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class delatedPricelistunits2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delatedPricelistunits2));
        
        string IMigrationMetadata.Id
        {
            get { return "202008061457250_delatedPricelistunits2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
