// <auto-generated />
namespace MainOffice.Migrations.AppDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class staff_concurrency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(staff_concurrency));
        
        string IMigrationMetadata.Id
        {
            get { return "202011270958090_staff_concurrency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
