// <auto-generated />
namespace MainOffice.Migrations.AppDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bills_row_version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bills_row_version));
        
        string IMigrationMetadata.Id
        {
            get { return "202103091558457_bills_row_version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
