// <auto-generated />
namespace MainOffice.Migrations.AppDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_PStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_PStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202104141537534_add_PStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
