//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainOffice.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainOffice.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительный телефон.
        /// </summary>
        public static string AdditionalPhone {
            get {
                return ResourceManager.GetString("AdditionalPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        public static string AddressGroupName {
            get {
                return ResourceManager.GetString("AddressGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string AddressName {
            get {
                return ResourceManager.GetString("AddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string ApplicationUser {
            get {
                return ResourceManager.GetString("ApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звания парикмахеров.
        /// </summary>
        public static string BarberLevelList {
            get {
                return ResourceManager.GetString("BarberLevelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование звания парикмахера.
        /// </summary>
        public static string BarberLevelName {
            get {
                return ResourceManager.GetString("BarberLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звание.
        /// </summary>
        public static string BarberLevelShortName {
            get {
                return ResourceManager.GetString("BarberLevelShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время завершения работы.
        /// </summary>
        public static string BillEndTime {
            get {
                return ResourceManager.GetString("BillEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи.
        /// </summary>
        public static string BillIssueDate {
            get {
                return ResourceManager.GetString("BillIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список счетов.
        /// </summary>
        public static string BillList {
            get {
                return ResourceManager.GetString("BillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер счета.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счет.
        /// </summary>
        public static string BillShortName {
            get {
                return ResourceManager.GetString("BillShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала работы.
        /// </summary>
        public static string BillStartTime {
            get {
                return ResourceManager.GetString("BillStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во БО.
        /// </summary>
        public static string BoQuantity {
            get {
                return ResourceManager.GetString("BoQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма БО.
        /// </summary>
        public static string BoSumm {
            get {
                return ResourceManager.GetString("BoSumm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время отмены.
        /// </summary>
        public static string CancelDateTime {
            get {
                return ResourceManager.GetString("CancelDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать что-то одно.
        /// </summary>
        public static string CannotChooseBoth {
            get {
                return ResourceManager.GetString("CannotChooseBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код должен состоять из цифр, от 1 до 999999.
        /// </summary>
        public static string CashRegCodeFormat {
            get {
                return ResourceManager.GetString("CashRegCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кода кассы.
        /// </summary>
        public static string CashRegCodeList {
            get {
                return ResourceManager.GetString("CashRegCodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код кассы.
        /// </summary>
        public static string CashRegCodeName {
            get {
                return ResourceManager.GetString("CashRegCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена со скидкой 1.
        /// </summary>
        public static string CashRegCodePrice10Name {
            get {
                return ResourceManager.GetString("CashRegCodePrice10Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена %1.
        /// </summary>
        public static string CashRegCodePrice10ShortName {
            get {
                return ResourceManager.GetString("CashRegCodePrice10ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена со скидкой 2.
        /// </summary>
        public static string CashRegCodePrice50Name {
            get {
                return ResourceManager.GetString("CashRegCodePrice50Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена %2.
        /// </summary>
        public static string CashRegCodePrice50ShortName {
            get {
                return ResourceManager.GetString("CashRegCodePrice50ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полная цена.
        /// </summary>
        public static string CashRegCodePriceName {
            get {
                return ResourceManager.GetString("CashRegCodePriceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string CashRegCodePriceShortName {
            get {
                return ResourceManager.GetString("CashRegCodePriceShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена сотрудника.
        /// </summary>
        public static string CashRegCodePriceStaffName {
            get {
                return ResourceManager.GetString("CashRegCodePriceStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена сотр..
        /// </summary>
        public static string CashRegCodePriceStaffShortName {
            get {
                return ResourceManager.GetString("CashRegCodePriceStaffShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кода.
        /// </summary>
        public static string CashRegCodeShortName {
            get {
                return ResourceManager.GetString("CashRegCodeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список клиентов.
        /// </summary>
        public static string ClientList {
            get {
                return ResourceManager.GetString("ClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент.
        /// </summary>
        public static string ClientShortName {
            get {
                return ResourceManager.GetString("ClientShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыто.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыл.
        /// </summary>
        public static string CloseEmployee {
            get {
                return ResourceManager.GetString("CloseEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место закрытия.
        /// </summary>
        public static string CloseGeoLocation {
            get {
                return ResourceManager.GetString("CloseGeoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время закрытия.
        /// </summary>
        public static string CloseOperationPoint {
            get {
                return ResourceManager.GetString("CloseOperationPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть рабочий лист.
        /// </summary>
        public static string CloseWorkSheet {
            get {
                return ResourceManager.GetString("CloseWorkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридический адрес.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предприятия.
        /// </summary>
        public static string CompanyList {
            get {
                return ResourceManager.GetString("CompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование предприятия.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предприятие.
        /// </summary>
        public static string CompanyShortName {
            get {
                return ResourceManager.GetString("CompanyShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-RU.
        /// </summary>
        public static string CurrentCulture {
            get {
                return ResourceManager.GetString("CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отложенное обновление.
        /// </summary>
        public static string DelayedUpdate {
            get {
                return ResourceManager.GetString("DelayedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверенны, что хотите удалить?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Депозит.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата увольнения.
        /// </summary>
        public static string DismissalDate {
            get {
                return ResourceManager.GetString("DismissalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уволен.
        /// </summary>
        public static string DismissalDateShortName {
            get {
                return ResourceManager.GetString("DismissalDateShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дубликат.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенные данные дублируют присутствующие в базе.
        /// </summary>
        public static string DuplicateDataError {
            get {
                return ResourceManager.GetString("DuplicateDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирует.
        /// </summary>
        public static string EditLock {
            get {
                return ResourceManager.GetString("EditLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список сотрудников.
        /// </summary>
        public static string EmployeeList {
            get {
                return ResourceManager.GetString("EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной салон.
        /// </summary>
        public static string EmployeeSalon {
            get {
                return ResourceManager.GetString("EmployeeSalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        public static string EmployeeShortName {
            get {
                return ResourceManager.GetString("EmployeeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пусто.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец работы.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выполнить действие. Данные связаны отложенными обновлениями.
        /// </summary>
        public static string ErrDelayedUpdateExists {
            get {
                return ResourceManager.GetString("ErrDelayedUpdateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка с получением данных о вашем местоположении..
        /// </summary>
        public static string ErrGeoLocation {
            get {
                return ResourceManager.GetString("ErrGeoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы запретили доступ к вашему местоположению..
        /// </summary>
        public static string ErrGeoLocationAccess {
            get {
                return ResourceManager.GetString("ErrGeoLocationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество символов в {0}, должно быть от {2} до {1}.
        /// </summary>
        public static string ErrNameLength {
            get {
                return ResourceManager.GetString("ErrNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия с операционным днем не доступны..
        /// </summary>
        public static string ErrOperDaySalon {
            get {
                return ResourceManager.GetString("ErrOperDaySalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выполнить действие. Введенные данные дублируют существующие активные данные .
        /// </summary>
        public static string ErrParentTableData {
            get {
                return ResourceManager.GetString("ErrParentTableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение цены должно быть от {1} до {2} грн..
        /// </summary>
        public static string ErrPriceRange {
            get {
                return ResourceManager.GetString("ErrPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите {0}.
        /// </summary>
        public static string ErrRequired {
            get {
                return ResourceManager.GetString("ErrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы находитесь далеко от салона..
        /// </summary>
        public static string FarAwayFromSalon {
            get {
                return ResourceManager.GetString("FarAwayFromSalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string FathersName {
            get {
                return ResourceManager.GetString("FathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите значения для показа.
        /// </summary>
        public static string FilterPrompt {
            get {
                return ResourceManager.GetString("FilterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтрация данных.
        /// </summary>
        public static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полная цена.
        /// </summary>
        public static string FullPrice {
            get {
                return ResourceManager.GetString("FullPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнено.
        /// </summary>
        public static string HasValue {
            get {
                return ResourceManager.GetString("HasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата принятия на работу.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принят.
        /// </summary>
        public static string HireDateShortName {
            get {
                return ResourceManager.GetString("HireDateShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутсвуют данные для списка выбора.
        /// </summary>
        public static string HtmlHelper_MissingSelectData {
            get {
                return ResourceManager.GetString("HtmlHelper_MissingSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выражение для списка выбора не является перечислением.
        /// </summary>
        public static string HtmlHelper_SelectExpressionNotEnumerable {
            get {
                return ResourceManager.GetString("HtmlHelper_SelectExpressionNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный тип данных для списка выбора.
        /// </summary>
        public static string HtmlHelper_WrongSelectDataType {
            get {
                return ResourceManager.GetString("HtmlHelper_WrongSelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядковый номер.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № п/п.
        /// </summary>
        public static string IndexShort {
            get {
                return ResourceManager.GetString("IndexShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальная скидка.
        /// </summary>
        public static string InitialPromo {
            get {
                return ResourceManager.GetString("InitialPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время внесения.
        /// </summary>
        public static string InsertDateTime {
            get {
                return ResourceManager.GetString("InsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP адрес.
        /// </summary>
        public static string IPAdress {
            get {
                return ResourceManager.GetString("IPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Касса.
        /// </summary>
        public static string Kasa {
            get {
                return ResourceManager.GetString("Kasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Широта.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долгота.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной телефон.
        /// </summary>
        public static string MainPhone {
            get {
                return ResourceManager.GetString("MainPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны выбрать продукцию или услугу.
        /// </summary>
        public static string MustChoose {
            get {
                return ResourceManager.GetString("MustChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не может быть пустым или null.
        /// </summary>
        public static string NullOrEmpty {
            get {
                return ResourceManager.GetString("NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Девичья фамилия.
        /// </summary>
        public static string OldFamilyName {
            get {
                return ResourceManager.GetString("OldFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дев. фамил..
        /// </summary>
        public static string OldFamilyShortName {
            get {
                return ResourceManager.GetString("OldFamilyShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыто.
        /// </summary>
        public static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыл.
        /// </summary>
        public static string OpenEmployee {
            get {
                return ResourceManager.GetString("OpenEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место открытия.
        /// </summary>
        public static string OpenGeoLocation {
            get {
                return ResourceManager.GetString("OpenGeoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время открытия.
        /// </summary>
        public static string OpenOperationPoint {
            get {
                return ResourceManager.GetString("OpenOperationPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть лист.
        /// </summary>
        public static string OpenWorkSheet {
            get {
                return ResourceManager.GetString("OpenWorkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата работы салона.
        /// </summary>
        public static string OperationDate {
            get {
                return ResourceManager.GetString("OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операционный день.
        /// </summary>
        public static string OperationDayArchiveShortName {
            get {
                return ResourceManager.GetString("OperationDayArchiveShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список операционных дней.
        /// </summary>
        public static string OperationDayArchiveShortNameList {
            get {
                return ResourceManager.GetString("OperationDayArchiveShortNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер для сортировки.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильный телефон.
        /// </summary>
        public static string PhoneNumber1Name {
            get {
                return ResourceManager.GetString("PhoneNumber1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон №1.
        /// </summary>
        public static string PhoneNumber1ShortName {
            get {
                return ResourceManager.GetString("PhoneNumber1ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительный телефон.
        /// </summary>
        public static string PhoneNumber2Name {
            get {
                return ResourceManager.GetString("PhoneNumber2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон №2.
        /// </summary>
        public static string PhoneNumber2ShortName {
            get {
                return ResourceManager.GetString("PhoneNumber2ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номера телефонов.
        /// </summary>
        public static string PhoneNumberGroupName {
            get {
                return ResourceManager.GetString("PhoneNumberGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделы прейскуранта.
        /// </summary>
        public static string PriceListUnitList {
            get {
                return ResourceManager.GetString("PriceListUnitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование раздела прейскуранта.
        /// </summary>
        public static string PriceListUnitName {
            get {
                return ResourceManager.GetString("PriceListUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел прейскуранта.
        /// </summary>
        public static string PriceListUnitShortName {
            get {
                return ResourceManager.GetString("PriceListUnitShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во напечатано.
        /// </summary>
        public static string PrintCountName {
            get {
                return ResourceManager.GetString("PrintCountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линии продуктов.
        /// </summary>
        public static string ProductlineList {
            get {
                return ResourceManager.GetString("ProductlineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование линии продуктов.
        /// </summary>
        public static string ProductlineName {
            get {
                return ResourceManager.GetString("ProductlineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линия.
        /// </summary>
        public static string ProductlineShortName {
            get {
                return ResourceManager.GetString("ProductlineShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список продукции.
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование продукта.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуга / Продукция.
        /// </summary>
        public static string ProductServiceName {
            get {
                return ResourceManager.GetString("ProductServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукция.
        /// </summary>
        public static string ProductShortName {
            get {
                return ResourceManager.GetString("ProductShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объемы продукта.
        /// </summary>
        public static string ProductVolumeList {
            get {
                return ResourceManager.GetString("ProductVolumeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование объема продукта.
        /// </summary>
        public static string ProductVolumeName {
            get {
                return ResourceManager.GetString("ProductVolumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объем.
        /// </summary>
        public static string ProductVolumeShortName {
            get {
                return ResourceManager.GetString("ProductVolumeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессии.
        /// </summary>
        public static string ProfessionList {
            get {
                return ResourceManager.GetString("ProfessionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название профессии.
        /// </summary>
        public static string ProfessionName {
            get {
                return ResourceManager.GetString("ProfessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессия.
        /// </summary>
        public static string ProfessionShortName {
            get {
                return ResourceManager.GetString("ProfessionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акция.
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату.
        /// </summary>
        public static string PromptDate {
            get {
                return ResourceManager.GetString("PromptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите {0}.
        /// </summary>
        public static string PromptEnter {
            get {
                return ResourceManager.GetString("PromptEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        public static string PStatus {
            get {
                return ResourceManager.GetString("PStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string QuantityShort {
            get {
                return ResourceManager.GetString("QuantityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформлен на предприятии.
        /// </summary>
        public static string RegisterCompany {
            get {
                return ResourceManager.GetString("RegisterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформлен.
        /// </summary>
        public static string RegisterCompanyShortName {
            get {
                return ResourceManager.GetString("RegisterCompanyShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата оформления.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата офор..
        /// </summary>
        public static string RegisterDateShortName {
            get {
                return ResourceManager.GetString("RegisterDateShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегестрирован(-а).
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегестрироваться.
        /// </summary>
        public static string RegisterSelf {
            get {
                return ResourceManager.GetString("RegisterSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to строк.
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Названия салонов.
        /// </summary>
        public static string SalonGroupName {
            get {
                return ResourceManager.GetString("SalonGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список салонов.
        /// </summary>
        public static string SalonList {
            get {
                return ResourceManager.GetString("SalonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название салона.
        /// </summary>
        public static string SalonName {
            get {
                return ResourceManager.GetString("SalonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список принтеров.
        /// </summary>
        public static string SalonPrinterList {
            get {
                return ResourceManager.GetString("SalonPrinterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование принтера.
        /// </summary>
        public static string SalonPrinterName {
            get {
                return ResourceManager.GetString("SalonPrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принтер.
        /// </summary>
        public static string SalonPrinterShortName {
            get {
                return ResourceManager.GetString("SalonPrinterShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя принтера в ОС.
        /// </summary>
        public static string SalonPrinterSysName {
            get {
                return ResourceManager.GetString("SalonPrinterSysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Салон.
        /// </summary>
        public static string SalonShortName {
            get {
                return ResourceManager.GetString("SalonShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статусы салона.
        /// </summary>
        public static string SalonStateList {
            get {
                return ResourceManager.GetString("SalonStateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование статуса.
        /// </summary>
        public static string SalonStateName {
            get {
                return ResourceManager.GetString("SalonStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string SalonStateShortName {
            get {
                return ResourceManager.GetString("SalonStateShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы салона.
        /// </summary>
        public static string SalonTypeList {
            get {
                return ResourceManager.GetString("SalonTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование типа.
        /// </summary>
        public static string SalonTypeName {
            get {
                return ResourceManager.GetString("SalonTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string SalonTypeShortName {
            get {
                return ResourceManager.GetString("SalonTypeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать все.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена продажи.
        /// </summary>
        public static string SellPrice {
            get {
                return ResourceManager.GetString("SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список услуг.
        /// </summary>
        public static string ServiceList {
            get {
                return ResourceManager.GetString("ServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование услуги.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги.
        /// </summary>
        public static string ServiceShortName {
            get {
                return ResourceManager.GetString("ServiceShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объемы услуги.
        /// </summary>
        public static string ServiceVolumeList {
            get {
                return ResourceManager.GetString("ServiceVolumeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование объема услуги.
        /// </summary>
        public static string ServiceVolumeName {
            get {
                return ResourceManager.GetString("ServiceVolumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объем.
        /// </summary>
        public static string ServiceVolumeShortName {
            get {
                return ResourceManager.GetString("ServiceVolumeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно содержать дату..
        /// </summary>
        public static string ShouldBeDate {
            get {
                return ResourceManager.GetString("ShouldBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер для печати счета.
        /// </summary>
        public static string StaffNumber {
            get {
                return ResourceManager.GetString("StaffNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID сотр..
        /// </summary>
        public static string StaffNumberShortName {
            get {
                return ResourceManager.GetString("StaffNumberShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во сотр. присутствует.
        /// </summary>
        public static string StaffQuantity {
            get {
                return ResourceManager.GetString("StaffQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сейчас с клиентом.
        /// </summary>
        public static string StaffQuantityBuisy {
            get {
                return ResourceManager.GetString("StaffQuantityBuisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        public static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало работы.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string Summ {
            get {
                return ResourceManager.GetString("Summ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма закрытых.
        /// </summary>
        public static string SummClosed {
            get {
                return ResourceManager.GetString("SummClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма в работе.
        /// </summary>
        public static string SummInWork {
            get {
                return ResourceManager.GetString("SummInWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтра.
        /// </summary>
        public static string TableFilters {
            get {
                return ResourceManager.GetString("TableFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонный номер должен быть формата (0XX) XXX-XX-XX.
        /// </summary>
        public static string TelFormat {
            get {
                return ResourceManager.GetString("TelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терминал.
        /// </summary>
        public static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торговые марки.
        /// </summary>
        public static string TrademarkList {
            get {
                return ResourceManager.GetString("TrademarkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование торговой марки.
        /// </summary>
        public static string TrademarkName {
            get {
                return ResourceManager.GetString("TrademarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТМ.
        /// </summary>
        public static string TrademarkShortName {
            get {
                return ResourceManager.GetString("TrademarkShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неоплачены.
        /// </summary>
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата обновления.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление.
        /// </summary>
        public static string UpdateDateShortName {
            get {
                return ResourceManager.GetString("UpdateDateShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить к дате.
        /// </summary>
        public static string UpdateToDate {
            get {
                return ResourceManager.GetString("UpdateToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык: Русский.
        /// </summary>
        public static string UserLanguage {
            get {
                return ResourceManager.GetString("UserLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завизировал.
        /// </summary>
        public static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виза скидки.
        /// </summary>
        public static string VisaPromo {
            get {
                return ResourceManager.GetString("VisaPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виза.
        /// </summary>
        public static string VisaShort {
            get {
                return ResourceManager.GetString("VisaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочий лист.
        /// </summary>
        public static string WorkSheet {
            get {
                return ResourceManager.GetString("WorkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочие листы.
        /// </summary>
        public static string WorkSheets {
            get {
                return ResourceManager.GetString("WorkSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный формат даты.
        /// </summary>
        public static string WrongDateFormat {
            get {
                return ResourceManager.GetString("WrongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат IP адреса.
        /// </summary>
        public static string WrongIpFormat {
            get {
                return ResourceManager.GetString("WrongIpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
