// <auto-generated />
namespace MainOffice.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_salon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_salon));
        
        string IMigrationMetadata.Id
        {
            get { return "202011161531178_user_salon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
