// <auto-generated />
namespace MainOffice.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_EmployeeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_EmployeeId));
        
        string IMigrationMetadata.Id
        {
            get { return "202008051004541_User_EmployeeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
